### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by larsbrinkhoff** [fsword7/mse#1]
Hello,

I'm curious if there are any plans for the future?  My special interest is PDP-10 emulation, so in particular I'm wondering about PDP-10 emulation in MSE.

These models are already well covered by other emulators: PDP-6, KA10, KI10, KL10 B, and KS10.  What's missing: KL10 A with RH10, Foonly.

**Comment by fsword7** [comment]
Yes, I have plans to implement PDP10 family on MSE emulator.  I am still working on device and memory auto-configuration and VAX family because MSE is based on MAME emulator for big computers as well as microcomputers.

**Comment by larsbrinkhoff** [comment]
Thank you.  Let me know if you want to run ITS on your emulator.  We have it running on KA10 and KS10, but not yet KL10.

**Comment by larsbrinkhoff** [comment]
From TS10: *"KL10 Processor still is under development at this time because I need to develop PDP-11 processor first for DTE20 interface."*

If this is still the case for MSE, that's very interesting for running ITS.  We have a KA10 emulator that can attach to separately running PDP-6 and PDP-11 emulators.

For ITS on a KL10, we have some data from the 11/40 front end file system that was stored on an RP04 disk.  I'm looking to make a bootable disk image and try it on a PDP-11 emulator.

**Comment by fsword7** [comment]
Yes, I am re-implementing PDP-11 and PDP-10 with new device base class soon.  I  did re-implemented VAX with new device class done.  I moved old files into old folder due to old device base class.  MSE already uses threads to handle multi processors. 

I was able boot RSX20 on TS10's PDP-11/40 emulator but DTE interface was not implemented yet.

**Comment by larsbrinkhoff** [comment]
That's great news!  This isn't available from GitHub yet, correct?

ITS uses KLDCP rather than RSX20 on the 11/40.

**Comment by fsword7** [comment]
Not yet.  I will look into KLDCP software.

**Comment by larsbrinkhoff** [comment]
Thanks.
